### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dansteele** [bogdanovich/ngrok-tunnel#14]
Heyo!
Firstly, great gem :) 👏 

Just started using Ngrok for the firs time in a while, and needed to use the region parameter. I ensured I was using the latest version, and checked the source code, but the region parameter was being ignored. It took me opening the gem to realise that your latest commits haven't been released yet 🤦‍♂️ 

Using the master branch for now, but suggest realeasing a new version of the gem 😄

**Comment by bogdanovich** [comment]
published
